### ISSUE TITLE
Finance on YARC

### ISSUE THREAD

**Issue by daxzimac** [tuxfuxch/yarc#10]
Dear Tuxfuxch,
I spoken to Massimiliano Magri, the owner of Grandinote.
We are in the high end market.
Our products are speakers, amplifiers and an audio streamer:
his name is Volta.

We can't wait to see the new :-)
and we would proude to finance on YARC, to get some functions important for our Volta.

Our need is to became YARC a "headless" interface for Audio.
A lot of our customers listen only music: they haven't a monitor.
So,
they have to be able to set the Volta and play music, without a monitor:
only by tablet, or smartphone.
For this reason, we need:
1) to mount NAS disk / disks
2) to add music in the Kodi libraries form a "FILE SEARCH" in NAS, hard drives....
3) to use the music add-ons like Tidal, Qobuz, Spotify...
4) others

POINT 1)
By a "FILE EXPLORE FUNCTION", we explore the resources:
maybe USB drivers, maybe a NAS.
For USB disks,no problems,
but if we try to enter in a NAS, we have 2 possibilities:
- the NAS is mounted, so no problems
- the NAS is unmounted, in YARC we need a window that permite the credentials edit for the NAS.
I think that for this operation, to mount the NAS in Linux could be sufficient.

POINT 2)
Always by the "FILE EXPLORE FUNCTION", we explore our resource
and we have to ADD albums and tracks inside the Kodi music libraries.
For this we followed your instructions:
- Add the source location to Kodi within the Kodi GUI
- Go to the added source (do not enter it). For example: Videos -> Files
- Open the context menu of the source
- Choose "add to Favorites"
- within Yarc you can now Brows it through Favorites
We need this function in the principal menu.
This function is very important.
Here we need also a research function
and to can put the album and the tracks in the Kodi libraries.

POINT 3)
Tidal, Qobuz, Spotify, Deezer, Youtube and others Kodi Add-Ons are managed by YARC,
but maybe that for headless use, some things have to be completed:
for example, to put inside their credentials, YARC doesn't present the smartphone keyboard.

POINT 4)
Others eventual things to get "headless" YARC.

If this cooperation is possible,
we would to know how much could be our contribute to do these modifications
and the required time, both for the current version and for the new.

If you will accept this work for us,
you also can to use all our modifies in the official application.
In this way, Kodi&YARC will became a wonderful alternative to MPD:
the famous headless music player!
A lot of people will be happy for this :-)

Waiting your nice answer,
all the best,
Daniele

**Comment by tuxfuxch** [comment]
Hi Daniele,
i have quite a stressful week and need some time to think about it, before i can give an answer. Please be patient until the weekend. then i will pick it up. Thanks in advance!

**Comment by tuxfuxch** [comment]
Hi Daniele, 
thanks for your patience. 
Point 1) this is not very easy to do and not out of the box with yarc, since it runs on client side. I think its possible, but yarc would need to run independent from Kodi.
Point 2) this is possible
Point 3) not sure if this is possible. i would need to do some research

i think we should have a phone (or skype or whatsapp) conversation. someone from your company with knowledge how you system is set up would be needed (i suppose a Linux with kodi installed?).
There are also some legal points i have to address, i am somewhat restricted there. Also what is going on with yarc since the last update, it's quite an exciting realease comming up.

could we have a phone call for example next week and clarify some points? I am living in the time zone gmt+1 (switzerland).

looking forward to hear from you.
