### ISSUE TITLE
Remain "button instead of swipe" activated after deleting webbrowser cache / cookie.

### ISSUE THREAD

**Issue by JustusDE** [tuxfuxch/yarc#8]
is this possible?

**Comment by tuxfuxch** [comment]
Hi Justus.
Sorry, i don't really get your issue. 

why do you want to delete cache and have this setting? i can't think of a reason for it. it might matter, because i can find a solution for this. 

the settings get saved in the browsers LocalStorage (which i think is cache...). so all of yarcs settings get deleted, or none (together with other settings, or setting from other webinterfaces).

if you explain better, i might find a solution. an update is anyway comming very soon, so changes can get into it, and you will have it soon.

**Comment by JustusDE** [comment]
I apologize for my bad english. I use the buttons instead of swipe on my laptop because it dont has a touchscreen. My Firefox is configurated to delete the cache and Cookies when i shut it down, thats why i have to set the option " button instead of swipe area" back everytime after a reboot. My question is if there is a possibility for me to change the code on kodi, to have the buttons allways on instead of swipe.

**Comment by tuxfuxch** [comment]
Hi, i think your english is not worse than mine :) i just did not really get it. now i do. thanks for making it clear to me.

it has nothing todo with kodi, it's an issue in yarc itselfe. right now, i can't think of an easy fix, and also not something i can implement in general. since most people have not this specific problem, and i can't think of something in general, i will not fix it.

however, you can change the code of yarc. are you can you code (at least a bit javascipt)? i can try to explain you, but you have to do it yourselfe, and after every update, you have to redo it. would that be acceptable?
i would tell you which lines you have to change in which file, and how. ok?

**Comment by JustusDE** [comment]
That would be more than acceptable. Thank you for the efforts :+1:

**Comment by tuxfuxch** [comment]
Hi, 
i think it's a pretty easy thing to do. but i did not test it, so please check it, and give feedback (also in case it works, that i can close the issue).

First you need to locate the addons folder of kodi. it depends on your operating system. it's in the same place as the folder "userdata", and it's called "addons". Here you can read where it is on your system:
http://kodi.wiki/view/Userdata.
so in case of Linux, it would be  	~/.kodi/addons/ 
in there is a folder "webinterface.yarc" (or something similar)
in there you have to find the file "resources/scripts/yarc.js"
the file "yarc.js" you have to open with an editor (not "ms word"  but better "Notepad" or something similar in case of windows)

now best you take the search function. in case you can't - happy finding :) it's very close to the end of the file, so if you search yourself, start at the bottom.

you should find a line which is:
`localStorageInit: function(){"`
now under it (or in there) there you find this
`if (!(yS.yS.hasOwnProperty('noSwipe'))) {`
`yS.yS.noSwipe = false`

here you change the second line to: 
`yS.yS.noSwipe = true`

Background info:
what happens: if yarc does not find settings (or a specific one) it generates them. the code around the place you do the changes are the default settings. the setting you want to change i called "noSwipe" which is by default false (not set). so if you change the default in the code to "true" (is set), the buttons will show by default.
i hope it works. otherwise we will find what i we did wrong, or find another solution.

good luck :) and don't forget to give feedback. thanks.

**Comment by JustusDE** [comment]
Hey,

I changed the line with sublime Text and then loaded it by ftp back to kodi. I rebooted both firefox and kodi, then opened the remote on firefox...it's still in swipe mode. I re-loaded the file to my computer to check it. looks like this:

 if (!(yS.yS.hasOwnProperty('noSwipe'))) {
           yS.yS.noSwipe = true;


Seems to be right ?

**Comment by tuxfuxch** [comment]
Hi, 
hm... it is right. i also tried it now by myself and it worked on my end.

as you wrote, you reloaded yarc on your firefox. this needs to be done. can you open the js file on firefox (for example with firebug, or with firefox built in webinspector (then debugger) if the changes are loaded?

logically it should work. in my test it works too. so there must be something else wrong as the theoretical and tested solution. i don't see a typo in your change. just changed to true and unlike my previous post with "";" in the end is right. i tried it on the coming version, but in this part there are no changes.
and since you wipe cache anyway, i think it's not a caching problem. 
do you have 2 different yarc installed and working with the other one?

**Comment by JustusDE** [comment]
It works !

I falsely put yarc.js in the wrong folder. ho ho

/storage/.kodi/addons/plugin.webinterface.yarc/webinterface.yarc/resources/scripts

instead of 

/storage/.kodi/addons/plugin.webinterface.yarc/resources/scripts

Thank you for your help and the great remote :)

**Comment by tuxfuxch** [comment]
Glad to hear and thanks for closing.
