### ISSUE TITLE
Open File button

### ISSUE THREAD

**Issue by daxzimac** [tuxfuxch/yarc#9]
Hello. First of all sorry for my English ...
The work you did is really impressive, very well done.
I have a need: a "open file / file" button that manages the opening of a multimedia file not present in the library.
Even better if you could manage the libraries directly from Yarc: add / remove sources, files, etc.
It's possible? And if it were, could you explain how, in broad terms?
Thanks in advance for any reply.

**Comment by tuxfuxch** [comment]
hi daxzimac,

well it's not on the roadmap yet to add/remove sources. I will upload a quite big update probably later this year, but i will not manage to add another feature since there is so much to do with the current update. 

BUT
if you have the source added to Kodi you actually can access it. You can achieve it the following way:
1) Add the source location to Kodi within the Kodi GUI - if not already done
2) Go to the added source within the Kodi GUI (do not enter it). For example: Videos -> Files
3) Open the context menu of the source within the Kodi GUI
4) Choose "add to Favorites"
5) Now, within Yarc you can now browse it through Favorites

I hope i translated right since my install is set to German. But i think you will get it. if not we can find out together.
I hope i got you right and you manage to solve you problem with my description, otherwise please ask again with some more details/explanations.
If you could solve your problem please tell me too.
Thanks and good luck

PS: sorry for my English too ;)

**Comment by tuxfuxch** [comment]
closed due to no reply
